name: smart_plant_app
description: Smart Plant Care Assistant & Gallery for Elderly Users in Myanmar.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # သက်ကြီးရွယ်အိုများအတွက် အသုံးပြုရန် ရိုးရှင်းသော UI
  cupertino_icons: ^1.0.6
  
  # အက်ပ်၏ ဦးနှောက် (Gemini AI)
  google_generative_ai: ^0.4.0
  
  # ကင်မရာ အသုံးပြုရန်
  camera: ^0.10.5+9
  
  # ဖုန်းထဲတွင် ဓာတ်ပုံနှင့် မှတ်တမ်းများ သိမ်းဆည်းရန် (Database)
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  
  # မိုးလေဝသ အချက်အလက် ယူရန်
  http: ^1.2.0
  
  # မှတ်ဉာဏ်ထိန်းချုပ်မှု (State Management)
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
