name: Manual Build APK

on:
  workflow_dispatch: # ဒီစာသားက Manual နှိပ်မှ Build ဖို့ ခွင့်ပြုတာပါ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # အသစ်ဆုံး version

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml # pubspec ထဲက version အတိုင်း သုံးမယ်

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-plant-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
